#lang info

; Original color scheme: https://github.com/Donearm/Ubaryd

(define deps '("base"))
(define pkg-desc "A port of Donearm's Ubaryd color scheme for DrRacket")
(define version "1.0.0")
(define pkg-authors '("Rebecca Turner"))

(define plain           #(#xf8 #xf6 #xf2))
(define snow            #(#xff #xff #xff))
(define coal            #(#x00 #x00 #x00))
(define bleaksand       #(#xc7 #xb3 #x86))
(define darksand        #(#x99 #x8f #x84))
(define gravel          #(#x98 #x91 #x89))
(define mediumsand      #(#x66 #x64 #x62))
(define deepgravel      #(#x45 #x41 #x3b))
(define deepergravel    #(#x35 #x32 #x2d))
(define darkgravel      #(#x24 #x23 #x21))
(define blackgravel     #(#x1c #x1b #x1a))
(define blackestgravel  #(#x14 #x14 #x13))
(define warmcorn        #(#xfa #xde #x3e))
(define lighttannedskin #(#xf4 #xcf #x86))
(define barcared        #(#xe2 #x5a #x74))
(define algae           #(#x70 #xd7 #x31))
(define warmadobe       #(#x9a #x48 #x20))
(define beachblue       #(#x41 #x63 #x89))
(define orange          #(#xff #xa7 #x24))
(define warmorange      #(#xff #x74 #x00))
(define bleaklemon      #(#xf9 #xef #x6d))
(define tannedumbrella  #(#xc1 #x4c #x3d))
(define toffee          #(#xb8 #x88 #x53))
(define nut             #(#xc7 #x91 #x5b))
(define cappuccino      #(#x88 #x63 #x3f))

(define framework:color-schemes
  `(#hash((name . "Ubaryd")
          (white-on-black-base? . #t)
          (colors
            .
            ((drracket:syncheck:document-identifier   ,beachblue)
             (drracket:syncheck:matching-identifiers  ,beachblue)
             (drracket:syncheck:tail-arrow            ,toffee)
             (drracket:syncheck:template-arrow        ,cappuccino)
             (drracket:syncheck:untacked              ,nut)
             (drracket:syncheck:unused-identifier     ,gravel)
             (drracket:syncheck:var-arrow             ,mediumsand)
             (framework:basic-canvas-background       ,blackestgravel)
             (framework:default-text-color            ,plain)
             (framework:misspelled-text-color         ,tannedumbrella)
             (framework:paren-match-color             ,deepergravel)

             ; style names
             ; valid symbols include 'bold, 'underline, 'italic
             ; and #s(background <color>)
             (drracket:check-syntax:free-variable                ,warmcorn)
             (drracket:check-syntax:imported                     ,barcared)
             (drracket:check-syntax:lexically-bound              ,beachblue)
             (drracket:check-syntax:set!d                        ,warmcorn)
             (drracket:check-syntax:my-obligation-style-pref     ,warmcorn)
             (drracket:check-syntax:their-obligation-style-pref  ,orange)
             (drracket:check-syntax:both-obligation-style-pref   ,bleaklemon)
             (drracket:check-syntax:unk-obligation-style-pref    ,plain)
             (drracket:check-syntax:unused-require               ,darksand)
             (drracket:read-eval-print-loop:error-color          ,barcared bold)
             (drracket:read-eval-print-loop:out-color            ,lighttannedskin)
             (drracket:read-eval-print-loop:value-color          ,beachblue)
             (framework:syntax-color:scheme:comment              ,gravel)
             (framework:syntax-color:scheme:constant             ,warmadobe italic)
             (framework:syntax-color:scheme:error                ,barcared bold)
             (framework:syntax-color:scheme:hash-colon-keyword   ,tannedumbrella)
             (framework:syntax-color:scheme:keyword              ,warmorange bold)
             (framework:syntax-color:scheme:other                ,plain)
             (framework:syntax-color:scheme:parenthesis          ,bleaksand)
             (framework:syntax-color:scheme:string               ,lighttannedskin)
             (framework:syntax-color:scheme:symbol               ,plain)
             (framework:syntax-color:scheme:text                 ,toffee)
             (plt:htdp:test-coverage-off                         ,barcared)
             (plt:htdp:test-coverage-on                          ,plain)
             (plt:module-language:test-coverage-off              ,barcared)
             (plt:module-language:test-coverage-on               ,plain))))))

